//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrydnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrydnik()
        {
            this.Zakazs = new HashSet<Zakaz>();
        }
    
        public int Id_Sotrydnik { get; set; }
        public string Familia { get; set; }
        public string Ima { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<int> Id_doljnosti { get; set; }
        public Nullable<decimal> Salary_per_hour { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Doljnost Doljnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakazs { get; set; }
    }
}
