//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ozon.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int Id_zakaz { get; set; }
        public Nullable<int> Id_buyer { get; set; }
        public Nullable<int> Id_sotrydnik { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> Id_tovar { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Id_point_of_issue { get; set; }
        public Nullable<decimal> Stoimost_zak { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Point_of_issue Point_of_issue { get; set; }
        public virtual Sotrydnik Sotrydnik { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
